BRATS = "BRATS"
HGG = "HGG"
LGG = "LGG"
BRATS_SLICE = 'BRATS-SLICE'

SEQUENCE_FLR = 'flr'
SEQUENCE_PDW = 'pdw'
SEQUENCE_T1C = 't1c'
SEQUENCE_T1P = 't1p'
SEQUENCE_T2W = 't2w'
SEQUENCES = (SEQUENCE_FLR, SEQUENCE_T1C, SEQUENCE_T1P, SEQUENCE_T2W, SEQUENCE_PDW)

SEQUENCE_FLAIR = 'flair'
SEQUENCE_T1CE  = 't1ce'
SEQUENCE_T1 = 't1'
SEQUENCE_T2 = 't2'
BRATS_SEQUENCES = (SEQUENCE_FLAIR, SEQUENCE_T1CE, SEQUENCE_T1, SEQUENCE_T2)

EXTENSION_MNC = '.mnc'
EXTENSION_MNC_GZ = '.mnc.gz'
EXTENSION_NII_GZ = '.nii.gz'
EXTENSIONS_NIB = (EXTENSION_MNC, EXTENSION_MNC_GZ, EXTENSION_NII_GZ)

EXTENSION_NPY = '.npy'
EXTENSION_NPZ = '.npz'
EXTENSIONS     = (EXTENSION_MNC, EXTENSION_MNC_GZ, EXTENSION_NII_GZ, EXTENSION_NPY, EXTENSION_NPZ)

LABEL_SEG = 'seg'
BRATS_LABELS = (LABEL_SEG,)

SUFFIX_BRATS = '.nii.gz'

MASK = 'mask'
const_MASK = "MASK"
const_SEG = "SEG"
const_MODS = "MODS"
const_PRE_GAD_MODS = "PRE_GAD_MODS"
const_POST_GAD_MODS = "POST_GAD_MODS"